server:
  port: 9001

spring:
  datasource:
     driver-class-name:
     url:
driverClassName: com.mysql.cj.jdbc.Driver
#dubbo配置
dubbo:
  application:
    name:  dubbo-server
  registry:
    address: 192.168.65.128:s
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000
